language: node_js
node_js:
    - "7"
    - "6"
script:
    - ./node_modules/.bin/eslint src
    - ./node_modules/.bin/jest
cache: yarn
after_success:
    echo "Wow it's successful'"
after_failure:
    echo "Wow it failed"
notifications:
    email:
        recipients:
            - ali.abdulhannan@gmail.com
        on_success: always
        on_failure: always